import { Poppins } from 'next/font/google';
import './globals.css';
import SessionProvider from './context/NextAuthProvider';
import { getServerSession } from 'next-auth';
import Layout from '@/components/Layout';
const inter = Poppins({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Layout>{children}</Layout>
        </SessionProvider>
      </body>
    </html>
  );
}
